ALTER TABLE bot_customer_note
  ADD COLUMN IF NOT EXISTS checked_by_admin BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS checked_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS checked_by_user_id BIGINT NULL;
